# .github/workflows/testing.yml
name: testing

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Cache Poetry
        id: cached-poetry-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: poetry install --with test,dev
        if: steps.cached-poetry-deps.outputs.cache-hit != 'true'

      - name: Code Standards
        run: |
          poetry run black .
          poetry run ruff -e --fix .

      - name: Execute tests
        run: poetry run pytest --disable-pytest-warnings

      - name: Merge to dev branch
        run: |
          git config user.email "${{ secrets.GIT_COMMITTER_EMAIL }}"
          git config user.name "${{ secrets.GIT_COMMITTER_NAME }}"
          git fetch --all
          git checkout ${{ secrets.GIT_TARGET_BRANCH_FOR_MERGE }}
          git merge --no-ff origin/${{ github.head_ref }}
          git push "https://${ secrets.GH_TOKEN_TEST }@github.com/cyuss/decathlon-turnover.git"

      # - name: Merge to dev branch
      #   uses: devmasx/merge-branch@master
      #   with:
      #     type: now
      #     # from_branch: ${{ github.head_ref }}
      #     target_branch: ${{ secrets.GIT_TARGET_BRANCH_FOR_MERGE }}
      #     github_token: ${{ github.token }}
